### ISSUE TITLE
example project

### ISSUE THREAD

**Issue by waywardm** [entozoon/slatest#1]
Hi there, I have been having trouble with slater also on windows It would be appreciated if I could see an example project, I currently use a modified supply theme on the older version of slate toolkit.

Regards Paul

**Comment by entozoon** [comment]
Hey, your wish is my command! Bam:
https://github.com/entozoon/slatest-example

Please be aware that you'll be, like, only the third person to use it so good luck.

**Comment by waywardm** [comment]
many thanks will give it a try.
