### ISSUE TITLE
To many redirects

### ISSUE THREAD

**Issue by driespieters** [entozoon/slatest#15]
Since a few days I'm getting a browser error "To many redirects" when running npm start.

The browser window url also keeps showing:
`https://mystore.com/services/access_tokens/create_sharing/48023765044?return_to=%2F%3Fkey%3D57b8dcccb91a7f7s74dfee3ef314` _(Side note: I've changed the acces tokens in the example)_

Have you had this issue before? 

_-If I start a theme preview from admin I can get it working_
_-Clearing cookies doesn't work_

**Comment by entozoon** [comment]
Oh dear, sorry to hear that. What version are you using? I recently published 2.2.2 which has some speed enhancements.

To be honest though, that looks more like a browser / Shopify issue. 
I wonder if the URL it's trying to open is correct? Perhaps you could compare the theme preview link in your admin to:
```https://${config.store}/?key=${config.appPassword}&preview_theme_id=${config.themeId}```

That is what we're using to create the link it opens with npm start. Nothing too clever

**Comment by entozoon** [comment]
UPDATE: I'm having the same problem myself.. what have Shopify gone and bloody changed! erm..

**Comment by entozoon** [comment]
I think they've knackered something up with their server redirects - so your thought about cookies was correct.
You can either clear cookies on your `https://mystore.com` and that fixes it, or open in incognito. Good luck!
