### ISSUE TITLE
npm WARN sass-loader@8.0.0 requires a peer of fibers@>= 3.1.0 but none is installed.

### ISSUE THREAD

**Issue by dav11d** [entozoon/slatest#2]
Any idea how to resolve this when installing ? Windows with gitbash

$ npm install slatest
npm WARN sass-loader@8.0.0 requires a peer of fibers@>= 3.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN babel-plugin-inferno@6.1.0 requires a peer of inferno@>=7 but none is installed. You must install peer dependencies yourself.
npm WARN @slater/theme@1.0.0 No repository field.

Trying to run npm start with WSL nix/subsystem also run into

/SLATEST/node_modules/slatest/lib/config.js:23
throw new Error(
^

Error: Please create a /mnt/c/Users/D/SLATEST/slatest.config.json file in your project dir!

even thought it exists

**Comment by entozoon** [comment]
Have you tried not using gitbash? 😜
I mean, it's entirely untested in bash/unix unfortunately. Built for your run-of-the-mill windows commant prompt.
Perhaps you could also tell me your `node -v` and `npm -v`..
as it's saying that your current working directory is `/mnt/c/Users/D/SLATEST/` which is, like, I dunno if that's correct or not

**Comment by dav11d** [comment]
yes, have tried powershell/cmd

still having the same issue
npm WARN sass-loader@8.0.0 requires a peer of fibers@>= 3.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN babel-plugin-inferno@6.1.0 requires a peer of inferno@>=7 but none is installed. You must install peer dependencies yourself.

**Comment by entozoon** [comment]
Well, those are just warnings. The error is the important part. 
I'd recommend upgrading node and npm at this point
