### ISSUE TITLE
Production deployment

### ISSUE THREAD

**Issue by driespieters** [entozoon/slatest#3]
Thanks for sharing this development toolkit!

Just a question: How do you handle deployment to a production environment? I currently have my project structure setup to have multiple config files. (Development, Staging & Production)

However the --upload-entire-theme command uploads the uncompiled version of the build. Is something like this possible?:
`  "scripts": {
    "start": "slatest",
    "build": "slatest --build",
    "deploy": "slatest --upload-entire-theme",
    "staging": "slatest --config slatest.config.staging.json --build --sound-effects --upload-entire-theme",
    "production": "slatest --config slatest.config.production.json --build --sound-effects --upload-entire-theme"
  },` 

Or can I somehow specify to upload the entire theme in production code? I currently run the build script before uploading.

Thanks!

**Comment by entozoon** [comment]
You're very welcome, glad it's useful to you!
I use it in the same way you described - with multiple config files. In some instances, with an Azure pipeline triggering the script.

The way you're trying to use it, with both `--build` and `--upload-entire-theme` flags is unexpected and I'm not sure what it'd do in the case. I tend to separate them out. i.e. the package script would look something like: 

```js
  "scripts": {
    "build": "slatest --build --config slatest.config.production.json",
    "deploy": "slatest --upload-entire-theme --config slatest.config.production.json"
}
```

Then your deploy process would involve running build and, on completion, running deploy.

**Comment by driespieters** [comment]
Thanks for the quick reply, really appreciate it!

Would changing the webpackConfig.mode to production be an option for the upload-entire-theme script? As this is probably isn't used for development and only in production. 

_(It's just so I don't forget to run the build script before the deploy script each time 🙂.)_

**Comment by entozoon** [comment]
You're welcome, I enjoy to help.

upload-entire-theme may well be used for development though, for example if you have a development store.

I do see what you're saying, and will think on it for future versions. At the minute, the way I see it is that upload-entire-theme does just that - uploading everything including the contents of the assets directory, in whatever state it's in (minified or otherwise).

Perhaps a short term solution could be a script line like:
```js 
"production": "npm run build && npm run deploy"
```
that might work well, good luck!
