### ISSUE TITLE
Does async/await support?

### ISSUE THREAD

**Issue by keidarcy** [entozoon/slatest#9]
```
Uncaught ReferenceError: regeneratorRuntime is not defined
```
I got this error, did I miss something? or just not support async/await?

**Comment by keidarcy** [comment]
```
You may need an additional loader to handle the result of these loaders.
|
|   debugger;
>   var products = JSON.parse(localStorage.getItem(STORAGE_PRODUCT_KEY)) ?? [];
```

and I get this error while webpack complies.
Do you have any idea that I can inject your webpack setting?

**Comment by entozoon** [comment]
Is that not an error in your code, rather than this package?

What version of node and npm are you using? I suggest you delete node_modules and re-install everything
